name: Jekyll site CI

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future" 
        git clone git@github.com:brakmic-aleksandar/brakmic-aleksandar.github.io.git target
        git config --global user.email "brakmic.aleksandar@gmail.com"
        git config --global user.name "Auto publisher"
        echo "cloned"
        cp -R ./_site/ ./target 
        echo "copied"
        cd ./target 
        echo "cd"
        git add . -f
        echo "add"
        git commit -m "auto publish" 
        echo "commit"
        git push
